import { collection, addDoc, getDocs, query, limit, where } from 'firebase/firestore';
import { db } from '../lib/firebase';

const MOCK_JOBS = [
  {
    title: "Head of Product Design",
    companyName: "Lumina Labs",
    companyLogo: "https://images.unsplash.com/photo-1549421263-5ec394a5ad4c?w=200&h=200&fit=crop",
    description: "Lead our design team into the next era of decentralized finance. We focus on brutalist minimalism and extreme usability.",
    requiredSkills: ["Product Design", "DeFi", "Figma", "Design Systems"],
    requiredLanguages: ["English"],
    experienceLevel: "lead",
    salaryRange: "$180k - $240k",
    location: { lat: 37.7749, lng: -122.4194, address: "San Francisco, CA" },
    companySize: "11-50",
    industry: "DeFi",
    companyMission: "Buidling the financial layer for the decentralized world.",
    mindset: "Move fast and break things, but make it beautiful.",
    culture: "Radical transparency and remote-first.",
    style: "Brutalist Minimalism",
    contractDetails: "Full-time, Equity: 0.5% - 1.0%",
    employerUid: "system-employer-1"
  },
  {
    title: "Senior AI researcher",
    companyName: "Aether AI",
    companyLogo: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=200&h=200&fit=crop",
    description: "Pioneering the next generation of transformer architectures. We are looking for researchers who want to solve AGI.",
    requiredSkills: ["Python", "PyTorch", "Transformers", "CUDA"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$250k - $350k",
    location: { lat: 37.4419, lng: -122.1430, address: "Palo Alto, CA" },
    companySize: "1-10",
    industry: "AI Research",
    companyMission: "Solving AGI using first principles.",
    mindset: "Academic rigor meets startup speed.",
    culture: "Research-driven, high autonomy.",
    style: "First Principles Thinking",
    contractDetails: "Full-time, Relocation package included.",
    employerUid: "system-employer-2"
  },
  {
    title: "Growth Engineer",
    companyName: "Velocity",
    companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop",
    description: "Build tools to optimize our user acquisition funnel. Data-driven experimentation is at our core.",
    requiredSkills: ["Next.js", "SQL", "Amplitude", "A/B Testing"],
    requiredLanguages: ["English", "German"],
    experienceLevel: "mid",
    salaryRange: "$110k - $150k",
    location: { lat: 52.5200, lng: 13.4050, address: "Berlin, DE" },
    companySize: "51-200",
    industry: "E-commerce",
    companyMission: "Making local shopping as fast as digital.",
    mindset: "Every pixel should convert.",
    culture: "Fast-paced, data-obsessed.",
    style: "Iterative / Experimental",
    contractDetails: "Full-time, Unlimited vacation.",
    employerUid: "system-employer-3"
  },
  {
    title: "Rust Core Developer",
    companyName: "SecureBlock",
    companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?w=200&h=200&fit=crop",
    description: "Building the world's most secure smart contract virtual machine. Security is not an afterthought.",
    requiredSkills: ["Rust", "Wasm", "Distributed Systems", "Cryptography"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$160k - $220k",
    location: { lat: 51.5074, lng: -0.1278, address: "London, UK" },
    mindset: "Zero-trust architecture.",
    culture: "Deep technical focus, quiet office.",
    style: "Functional / Memory Safe",
    contractDetails: "Contract-to-hire (6 months)",
    employerUid: "system-employer-4"
  },
  {
    title: "Fullstack Product Engineer",
    companyName: "Mosaic",
    companyLogo: "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=200&h=200&fit=crop",
    description: "Help us build the most intuitive workspace for creative professionals. You own features from end-to-end.",
    requiredSkills: ["Typescript", "PostgreSQL", "Vercel", "Tailwind"],
    requiredLanguages: ["English", "French"],
    experienceLevel: "mid",
    salaryRange: "$120k - $160k",
    location: { lat: 48.8566, lng: 2.3522, address: "Paris, FR" },
    mindset: "Empathy for the user above all.",
    culture: "Creative, diverse, art-loving.",
    style: "Design-led engineering",
    contractDetails: "Full-time, Health insurance + Gym",
    employerUid: "system-employer-5"
  },
  {
    title: "Lead Frontend Architect",
    companyName: "Nexus UI",
    companyLogo: "https://images.unsplash.com/photo-1572044162444-ad60f128bde2?w=200&h=200&fit=crop",
    description: "We are building a revolutionary design tool for spatial computing. We need someone who can push React and WebGL to their limits.",
    requiredSkills: ["React", "WebGL", "Three.js", "Performance Optimization"],
    requiredLanguages: ["English"],
    experienceLevel: "lead",
    salaryRange: "$200k - $260k",
    location: { lat: 34.0522, lng: -118.2437, address: "Los Angeles, CA" },
    mindset: "The interface is the product.",
    culture: "Highly collaborative, design-obsessed.",
    style: "Spatial / Interactive",
    contractDetails: "Full-time, Remote potential.",
    employerUid: "system-employer-6"
  },
  {
    title: "Backend Scale Engineer",
    companyName: "Astra Cloud",
    companyLogo: "https://images.unsplash.com/photo-1550741111-3d5d11cd5a1d?w=200&h=200&fit=crop",
    description: "Help us scale our real-time messaging engine to handle millions of concurrent users. Go and Kubernetes are our bread and butter.",
    requiredSkills: ["Go", "Kubernetes", "Redis", "Distributed Systems"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$170k - $230k",
    location: { lat: 40.7128, lng: -74.0060, address: "New York, NY" },
    mindset: "Redundancy is king.",
    culture: "Engineering-first, no BS.",
    style: "Pragmatic / Robust",
    contractDetails: "Full-time, Stock options.",
    employerUid: "system-employer-7"
  },
  {
    title: "UX Researcher (Discovery)",
    companyName: "Spark Social",
    companyLogo: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=200&h=200&fit=crop",
    description: "Understand the hidden motivations behind social connection. We need researchers who love human psychology as much as data.",
    requiredSkills: ["User Interviews", "Usability Testing", "Psychology", "Mixpanel"],
    requiredLanguages: ["English", "Spanish"],
    experienceLevel: "mid",
    salaryRange: "$100k - $140k",
    location: { lat: 25.7617, lng: -80.1918, address: "Miami, FL" },
    mindset: "Listen more than you speak.",
    culture: "Diverse, vibrant, empathetic.",
    style: "Human-Centric",
    contractDetails: "Full-time, Hybrid.",
    employerUid: "system-employer-8"
  },
  {
    title: "Mobile App Wizard",
    companyName: "SnapLeap",
    companyLogo: "https://images.unsplash.com/photo-1614850523296-62c0993079f0?w=200&h=200&fit=crop",
    description: "Building the next big thing in AR gaming. If you love Swift and ARKit, we want you.",
    requiredSkills: ["Swift", "SwiftUI", "ARKit", "Metal"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$160k - $210k",
    location: { lat: 37.7749, lng: -122.4194, address: "San Francisco, CA" },
    mindset: "Play is the highest form of research.",
    culture: "Fun, experimental, high energy.",
    style: "Playful / Polish",
    contractDetails: "Full-time.",
    employerUid: "system-employer-9"
  },
  {
    title: "Security & Privacy Lead",
    companyName: "Fortress Tech",
    companyLogo: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&h=200&fit=crop",
    description: "Protect user data in an increasingly transparent world. Focus on zero-knowledge proofs and encryption.",
    requiredSkills: ["Cybersecurity", "Cryptography", "Security Auditing", "ZKP"],
    requiredLanguages: ["English"],
    experienceLevel: "lead",
    salaryRange: "$190k - $250k",
    location: { lat: 47.6062, lng: -122.3321, address: "Seattle, WA" },
    mindset: "Privacy is a human right.",
    culture: "Security-conscious, methodical.",
    style: "Hardened / Private",
    contractDetails: "Full-time.",
    employerUid: "system-employer-10"
  },
  {
    title: "Data Platform Architect",
    companyName: "Inflow Data",
    companyLogo: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&h=200&fit=crop",
    description: "Build the data backbone for the world's largest retailers. We deal with petabytes of data daily.",
    requiredSkills: ["SQL", "Spark", "Airflow", "Cloud Platforms"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$150k - $200k",
    location: { lat: 32.7767, lng: -96.7970, address: "Dallas, TX" },
    mindset: "Efficiency at scale.",
    culture: "Scale-focused, results-driven.",
    style: "Analytical / Scalable",
    contractDetails: "Full-time.",
    employerUid: "system-employer-11"
  },
  {
    title: "Creative Technologist",
    companyName: "Articube",
    companyLogo: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=200&h=200&fit=crop",
    description: "Bridge the gap between art and code. You'll build interactive installations and immersive digital experiences.",
    requiredSkills: ["Creative Coding", "Three.js", "Python", "Generative AI"],
    requiredLanguages: ["English", "French"],
    experienceLevel: "mid",
    salaryRange: "$110k - $160k",
    location: { lat: 48.8566, lng: 2.3522, address: "Paris, FR" },
    mindset: "Code is a medium for art.",
    culture: "Artistic, experimental, multidisciplinary.",
    style: "Avant-Garde",
    contractDetails: "Project-based / Full-time.",
    employerUid: "system-employer-12"
  },
  {
    title: "Fintech Lead Developer",
    companyName: "Quantico",
    companyLogo: "https://images.unsplash.com/photo-1611974715855-958e0ad39ee5?w=200&h=200&fit=crop",
    description: "Reinventing the trading experience for Gen Z. Speed, security, and social features are key.",
    requiredSkills: ["Typescript", "Node.js", "PostgreSQL", "Kafka"],
    requiredLanguages: ["English"],
    experienceLevel: "lead",
    salaryRange: "$220k - $300k",
    location: { lat: 40.7128, lng: -74.0060, address: "New York, NY" },
    mindset: "Finance for everyone.",
    culture: "Fast-paced, regulated but agile.",
    style: "Slick / Social",
    contractDetails: "Full-time.",
    employerUid: "system-employer-13"
  },
  {
    title: "Brand Strategy Director",
    companyName: "Vivid Agency",
    companyLogo: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=200&h=200&fit=crop",
    description: "Define the voice and visual identity for tomorrow's iconic brands.",
    requiredSkills: ["Branding", "Strategy", "Copywriting", "Art Direction"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$160k - $220k",
    location: { lat: 34.0522, lng: -118.2437, address: "Los Angeles, CA" },
    mindset: "Stories win.",
    culture: "Creative, diverse, bold.",
    style: "Narrative-driven",
    contractDetails: "Full-time.",
    employerUid: "system-employer-14"
  },
  {
    title: "DevOps Champion",
    companyName: "OpsFlow",
    companyLogo: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200&h=200&fit=crop",
    description: "Automate everything from deployment to incident response. We target 99.999% uptime.",
    requiredSkills: ["Terraform", "AWS", "CI/CD", "Monitoring"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$150k - $190k",
    location: { lat: 37.7749, lng: -122.4194, address: "San Francisco, CA" },
    mindset: "Stability is a feature.",
    culture: "On-call is a culture of learning.",
    style: "Automated / Resilient",
    contractDetails: "Full-time.",
    employerUid: "system-employer-15"
  },
  {
    title: "Junior Product Designer",
    companyName: "BaseCamp",
    companyLogo: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=200&h=200&fit=crop",
    description: "Perfect opportunity for a talented junior to learn design systems and user research in a fast-paced environment.",
    requiredSkills: ["Figma", "UI Design", "Prototyping"],
    requiredLanguages: ["English"],
    experienceLevel: "junior",
    salaryRange: "$70k - $90k",
    location: { lat: 41.8781, lng: -87.6298, address: "Chicago, IL" },
    mindset: "Learn and iterate.",
    culture: "Mentorship-focused, humble.",
    style: "Clean / Functional",
    contractDetails: "Full-time.",
    employerUid: "system-employer-16"
  },
  {
    title: "Senior Android Dev",
    companyName: "GreenDroid",
    companyLogo: "https://images.unsplash.com/photo-1607705703571-c5a8695f18f6?w=200&h=200&fit=crop",
    description: "Build the most sustainable mobile os layer. Kotlin and low-level performance are key.",
    requiredSkills: ["Kotlin", "Android SDK", "Jetpack Compose", "Coroutines"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$160k - $210k",
    location: { lat: 52.5200, lng: 13.4050, address: "Berlin, DE" },
    mindset: "Green tech first.",
    culture: "Eco-conscious, technical.",
    style: "Modern / Performant",
    contractDetails: "Full-time.",
    employerUid: "system-employer-17"
  },
  {
    title: "Customer Experience Lead",
    companyName: "ZenDesk (Partner)",
    companyLogo: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=200&h=200&fit=crop",
    description: "Lead the Support team to deliver world-class service using the latest AI support tools.",
    requiredSkills: ["Customer Success", "Leadership", "Zendesk", "AI Ops"],
    requiredLanguages: ["English", "Mandarin"],
    experienceLevel: "lead",
    salaryRange: "$130k - $170k",
    location: { lat: 1.3521, lng: 103.8198, address: "Singapore" },
    mindset: "Happy customers, happy life.",
    culture: "Service-oriented, global.",
    style: "Warm / Efficient",
    contractDetails: "Full-time.",
    employerUid: "system-employer-18"
  },
  {
    title: "Open Source Advocate",
    companyName: "GitGud",
    companyLogo: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=200&h=200&fit=crop",
    description: "Represent our company in the open source world. Contribute to major projects and host community events.",
    requiredSkills: ["Public Speaking", "Community Management", "Open Source", "Technical Writing"],
    requiredLanguages: ["English"],
    experienceLevel: "senior",
    salaryRange: "$140k - $190k",
    location: { lat: 51.5074, lng: -0.1278, address: "London, UK" },
    mindset: "Giving back is the goal.",
    culture: "Community-driven, outward-facing.",
    style: "Transparent / Open",
    contractDetails: "Full-time.",
    employerUid: "system-employer-19"
  },
  {
    title: "Web3 Fullstack Engineer",
    companyName: "DegenSoft",
    companyLogo: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&h=200&fit=crop",
    description: "Build the front and back of the most advanced NFT marketplace. We move fast.",
    requiredSkills: ["React", "Solidity", "Ethers.js", "Node.js"],
    requiredLanguages: ["English"],
    experienceLevel: "mid",
    salaryRange: "$130k - $180k",
    location: { lat: 25.7617, lng: -80.1918, address: "Miami, FL" },
    mindset: "WAGMI.",
    culture: "Fast, wild, lucrative.",
    style: "Degenerative / Hypergrowth",
    contractDetails: "Full-time.",
    employerUid: "system-employer-20"
  }
];

const MOCK_CANDIDATES = [
  {
    displayName: "Alex Rivera",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    bio: "Fullstack engineer with a passion for creative coding and generative art. 8 years of experience in high-growth startups.",
    skills: ["React", "Three.js", "WebGL", "Node.js"],
    languages: ["English", "Spanish"],
    experienceLevel: "senior",
    location: { lat: 34.0522, lng: -118.2437, address: "Los Angeles, CA" },
    githubUrl: "https://github.com/arivera",
    desiredSkills: ["Rust", "Wasm"],
    mindset: "Craftsmanship and performance above all.",
    culture: "Collaborative and focus-driven.",
    style: "Clean Code / Modular Architecture",
    desiredSalary: "$170k",
    uid: "system-candidate-1"
  },
  {
    displayName: "Sophie Chen",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop",
    bio: "Data Scientist specializing in transformer models and recommendation engines. Former PhD researcher.",
    skills: ["Python", "TensorFlow", "Scikit-learn", "SQL"],
    languages: ["English", "Mandarin"],
    experienceLevel: "senior",
    location: { lat: 40.7128, lng: -74.0060, address: "New York, NY" },
    githubUrl: "https://github.com/schen-data",
    desiredSkills: ["Go", "Kubernetes"],
    mindset: "The data never lies.",
    culture: "Intellectually curious, low ego.",
    style: "Research-driven / Peer Reviewed",
    desiredSalary: "$190k",
    uid: "system-candidate-2"
  },
  {
    displayName: "Jordan Miles",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop",
    bio: "Mobile developer who loves building slick, high-performance iOS apps. Swift is my native language.",
    skills: ["Swift", "SwiftUI", "Core Data", "Combine"],
    languages: ["English"],
    experienceLevel: "mid",
    location: { lat: 37.7749, lng: -122.4194, address: "San Francisco, CA" },
    githubUrl: "https://github.com/jmiles-ios",
    desiredSkills: ["React Native", "Flutter"],
    mindset: "Animations should be 60fps or it's a bug.",
    culture: "Energetic and feedback-rich.",
    style: "Reactive / Declarative",
    desiredSalary: "$140k",
    uid: "system-candidate-3"
  },
  {
    displayName: "Elena Petrova",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop",
    bio: "Cybersecurity analyst turned DevSecOps engineer. I make sure your pipeline is as secure as it is fast.",
    skills: ["Docker", "Terraform", "AWS", "Security Auditing"],
    languages: ["English", "Russian"],
    experienceLevel: "mid",
    location: { lat: 52.3676, lng: 4.9041, address: "Amsterdam, NL" },
    githubUrl: "https://github.com/epetrova-sec",
    desiredSkills: ["Haskell", "Solidity"],
    mindset: "Everything that can be automated, should be.",
    culture: "Reliable and system-oriented.",
    style: "Immutable Infrastructure",
    desiredSalary: "€95k",
    uid: "system-candidate-4"
  },
  {
    displayName: "Marcus Wang",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop",
    bio: "UX Researcher with a background in cognitive psychology. I love diving deep into user friction.",
    skills: ["User Interviews", "Usability Testing", "Mixpanel", "Figma"],
    languages: ["English", "Cantonese"],
    experienceLevel: "senior",
    location: { lat: 22.3193, lng: 114.1694, address: "Hong Kong, HK" },
    githubUrl: "https://github.com/mwang-ux",
    desiredSkills: ["Python", "R"],
    mindset: "Ask 'why' five times.",
    culture: "Empathetic and inquisitive.",
    style: "Evidence-based Design",
    desiredSalary: "$150k",
    uid: "system-candidate-5"
  },
  {
    displayName: "Lucas Fischer",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=600&fit=crop",
    bio: "Platform engineer obsessed with Kubernetes and service mesh. 6 years of experience in distributed systems.",
    skills: ["Go", "Kubernetes", "Redis", "Distributed Systems"],
    languages: ["English", "German"],
    experienceLevel: "senior",
    location: { lat: 52.5200, lng: 13.4050, address: "Berlin, DE" },
    githubUrl: "https://github.com/lfischer-cloud",
    linkedinUrl: "https://linkedin.com/in/lucas-fischer-dev",
    desiredSkills: ["Rust", "eBPF"],
    mindset: "Infrastructure is code.",
    culture: "Technical autonomy, clear docs.",
    style: "Robust / Scalable",
    desiredSalary: "€110k",
    uid: "system-candidate-6"
  },
  {
    displayName: "Maya Patel",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop",
    bio: "Product designer focusing on Design Systems and Accessibility. I building tools that help teams scale.",
    skills: ["Product Design", "Figma", "Design Systems", "Accessibility"],
    languages: ["English", "Hindi"],
    experienceLevel: "senior",
    location: { lat: 12.9716, lng: 77.5946, address: "Bangalore, IN" },
    githubUrl: "https://github.com/mpatel-design",
    linkedinUrl: "https://linkedin.com/in/maya-patel-ux",
    desiredSkills: ["React", "Typescript"],
    mindset: "Consistency is usable.",
    culture: "Collaborative, mentor-focused.",
    style: "Systematic / Accessible",
    desiredSalary: "$120k",
    uid: "system-candidate-7"
  },
  {
    displayName: "Dante Rossi",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop",
    bio: "Frontend dev with a heavy focus on performance and micro-animations. Framer Motion is my go-to.",
    skills: ["React", "Performance Optimization", "Three.js", "Framer Motion"],
    languages: ["English", "Italian"],
    experienceLevel: "senior",
    location: { lat: 41.9028, lng: 12.4964, address: "Rome, IT" },
    githubUrl: "https://github.com/drossi-ui",
    desiredSkills: ["Unity", "C#"],
    mindset: "Fluidity is the goal.",
    culture: "Creative, fast-paced.",
    style: "Interactive / Polish",
    desiredSalary: "€85k",
    uid: "system-candidate-8"
  },
  {
    displayName: "Sarah Jenkins",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop",
    bio: "Brand strategist and copywriter. I help startups find their voice and visual identity.",
    skills: ["Branding", "Strategy", "Copywriting", "Art Direction"],
    languages: ["English"],
    experienceLevel: "senior",
    location: { lat: 51.5074, lng: -0.1278, address: "London, UK" },
    githubUrl: "https://github.com/sjenkins-creative",
    desiredSkills: ["Figma", "Storytelling"],
    mindset: "Clarity over cleverness.",
    culture: "Bold, narrative-driven.",
    style: "Minimalist / Punchy",
    desiredSalary: "£100k",
    uid: "system-candidate-9"
  },
  {
    displayName: "Kenji Sato",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=600&fit=crop",
    bio: "Backend engineer specializing in distributed databases and stream processing. Big fan of Kafka.",
    skills: ["Typescript", "Node.js", "PostgreSQL", "Kafka"],
    languages: ["English", "Japanese"],
    experienceLevel: "senior",
    location: { lat: 35.6762, lng: 139.6503, address: "Tokyo, JP" },
    githubUrl: "https://github.com/ksato-backend",
    desiredSkills: ["Rust", "Scala"],
    mindset: "Reliable over fast.",
    culture: "Methodical, technical.",
    style: "Clean / Robust",
    desiredSalary: "¥15M",
    uid: "system-candidate-10"
  },
  {
    displayName: "Zoe Miller",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=600&fit=crop",
    bio: "Growth focused fullstack engineer. I love running experiments and seeing metrics move.",
    skills: ["Next.js", "SQL", "Amplitude", "A/B Testing"],
    languages: ["English"],
    experienceLevel: "mid",
    location: { lat: 37.7749, lng: -122.4194, address: "San Francisco, CA" },
    githubUrl: "https://github.com/zmiller-growth",
    desiredSkills: ["React Native", "Python"],
    mindset: "Iterate to win.",
    culture: "Metrics-driven, fast.",
    style: "Experimental",
    desiredSalary: "$150k",
    uid: "system-candidate-11"
  },
  {
    displayName: "Liam O'Connor",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=600&fit=crop",
    bio: "Security engineer with a focus on Cryptography and ZKP. I'm building a more private web.",
    skills: ["Cybersecurity", "Cryptography", "Security Auditing", "ZKP"],
    languages: ["English", "Irish"],
    experienceLevel: "senior",
    location: { lat: 53.3498, lng: -6.2603, address: "Dublin, IE" },
    githubUrl: "https://github.com/loconnor-sec",
    desiredSkills: ["Wasm", "Rust"],
    mindset: "Trust no one.",
    culture: "Privacy-centric, thorough.",
    style: "Hardened",
    desiredSalary: "€100k",
    uid: "system-candidate-12"
  },
  {
    displayName: "Clara Dubois",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=400&h=600&fit=crop",
    bio: "Three.js wizard and creative coder. I turn ideas into immersive bits.",
    skills: ["Creative Coding", "Three.js", "WebGL", "Framer Motion"],
    languages: ["English", "French"],
    experienceLevel: "mid",
    location: { lat: 48.8566, lng: 2.3522, address: "Paris, FR" },
    githubUrl: "https://github.com/cdubois-art",
    desiredSkills: ["Shaders", "Unity"],
    mindset: "Code is magic.",
    culture: "Artistic, diverse.",
    style: "Experimental / Visual",
    desiredSalary: "€75k",
    uid: "system-candidate-13"
  },
  {
    displayName: "Ahmed Mansour",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=400&h=600&fit=crop",
    bio: "DevOps engineer focusing on AWS and Terraform. I target 5 nines of availability.",
    skills: ["Docker", "Terraform", "AWS", "Monitoring"],
    languages: ["English", "Arabic"],
    experienceLevel: "senior",
    location: { lat: 25.2048, lng: 55.2708, address: "Dubai, AE" },
    githubUrl: "https://github.com/amansour-ops",
    desiredSkills: ["CI/CD", "Pulumi"],
    mindset: "Automation is the key.",
    culture: "Stable, high availability.",
    style: "Automated",
    desiredSalary: "$140k",
    uid: "system-candidate-14"
  },
  {
    displayName: "Isabella Silva",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1491349174775-aaafddd81942?w=400&h=600&fit=crop",
    bio: "Mobile developer obsessed with Kotlin and low-level performance.",
    skills: ["Kotlin", "Android SDK", "Jetpack Compose", "Coroutines"],
    languages: ["English", "Portuguese"],
    experienceLevel: "mid",
    location: { lat: -23.5505, lng: -46.6333, address: "São Paulo, BR" },
    githubUrl: "https://github.com/isilva-android",
    desiredSkills: ["Swift", "Wasm"],
    mindset: "Modern Android only.",
    culture: "Technical, fast.",
    style: "Performant / Modern",
    desiredSalary: "$100k",
    uid: "system-candidate-15"
  },
  {
    displayName: "Noah Wright",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=600&fit=crop",
    bio: "Customer Success lead who loves building systems that scale empathy.",
    skills: ["Customer Success", "Leadership", "Zendesk", "Mixpanel"],
    languages: ["English"],
    experienceLevel: "lead",
    location: { lat: 45.4215, lng: -75.6972, address: "Ottawa, CA" },
    githubUrl: "https://github.com/nwright-cs",
    desiredSkills: ["AI Ops", "Data Analysis"],
    mindset: "Service is leadership.",
    culture: "Warm, empathetic.",
    style: "Efficient / Human",
    desiredSalary: "$120k",
    uid: "system-candidate-16"
  },
  {
    displayName: "Eva Novak",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?w=400&h=600&fit=crop",
    bio: "Open source advocate and technical writer. I love bridge building between engineers and users.",
    skills: ["Public Speaking", "Community Management", "Open Source", "Technical Writing"],
    languages: ["English"],
    experienceLevel: "senior",
    location: { lat: 50.0755, lng: 14.4378, address: "Prague, CZ" },
    githubUrl: "https://github.com/enovak-oss",
    desiredSkills: ["Go", "React"],
    mindset: "Knowledge should be free.",
    culture: "Community-driven.",
    style: "Transparent / Clear",
    desiredSalary: "€90k",
    uid: "system-candidate-17"
  },
  {
    displayName: "Samuel Jackson",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=600&fit=crop",
    bio: "Web3 engineer pushing the boundaries of NFT marketplaces.",
    skills: ["React", "Solidity", "Ethers.js", "Node.js"],
    languages: ["English"],
    experienceLevel: "senior",
    location: { lat: 40.7128, lng: -74.0060, address: "New York, NY" },
    githubUrl: "https://github.com/sjackson-web3",
    desiredSkills: ["Rust", "PostgreSQL"],
    mindset: "Decentralize everything.",
    culture: "Wild, fast-paced.",
    style: "Degenerative",
    desiredSalary: "$200k",
    uid: "system-candidate-18"
  },
  {
    displayName: "Olivia Brooks",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop",
    bio: "Junior product designer looking to make an impact in the social space.",
    skills: ["Figma", "UI Design", "User Interviews", "USability Testing"],
    languages: ["English"],
    experienceLevel: "junior",
    location: { lat: 34.0522, lng: -118.2437, address: "Los Angeles, CA" },
    githubUrl: "https://github.com/obrooks-ui",
    desiredSkills: ["Product Strategy", "Growth"],
    mindset: "Empathy first.",
    culture: "Small teams, big impact.",
    style: "Warm / Minimalist",
    desiredSalary: "$85k",
    uid: "system-candidate-19"
  },
  {
    displayName: "David Lee",
    role: "candidate",
    photoURL: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop",
    bio: "Fullstack engineer who loves building tools for creative people.",
    skills: ["Next.js", "Typescript", "Vercel", "Tailwind"],
    languages: ["English", "Mandarin"],
    experienceLevel: "senior",
    location: { lat: 22.3193, lng: 114.1694, address: "Hong Kong, HK" },
    githubUrl: "https://github.com/dlee-product",
    desiredSkills: ["Figma", "Product Design"],
    mindset: "Tools define work.",
    culture: "Engineering meets design.",
    style: "Polished / Product-led",
    desiredSalary: "$160k",
    uid: "system-candidate-20"
  }
];

export async function seedMockData(currentUserUid?: string, role?: string) {
  try {
    const jobsRef = collection(db, 'jobs');
    const profilesRef = collection(db, 'profiles');
    
    // Seed Jobs for Candidates
    if (role === 'candidate') {
      const snap = await getDocs(query(jobsRef, limit(10)));
      if (snap.size < 10) {
        console.log("Seeding mock jobs for candidate discovery...");
        for (const job of MOCK_JOBS) {
          await addDoc(jobsRef, {
            ...job,
            createdAt: Date.now()
          });
        }
      }
    }

    // Seed Candidates for Employers
    if (role === 'employer') {
      const snap = await getDocs(query(profilesRef, where('role', '==', 'candidate'), limit(10)));
      if (snap.size < 10) {
        console.log("Seeding mock candidates for employer discovery...");
        for (const candidate of MOCK_CANDIDATES) {
          await addDoc(profilesRef, {
            ...candidate,
            createdAt: Date.now()
          });
        }
      }
      
      // Also seed some jobs if the employer has none
      const myJobsSnap = await getDocs(query(jobsRef, where('employerUid', '==', currentUserUid), limit(1)));
      if (myJobsSnap.empty && currentUserUid) {
        console.log("Seeding initial jobs for employer...");
        for (const job of MOCK_JOBS.slice(0, 5)) {
          await addDoc(jobsRef, {
            ...job,
            employerUid: currentUserUid,
            createdAt: Date.now()
          });
        }
      }
    }
  } catch (error) {
    console.error("Mock seeding failed:", error);
  }
}
