export function createSeed() {
  const now = Date.now();
  return {
    users: [
      { id: 'candidate-demo', role: 'candidate', demo: true, name: 'Alex Morgan', email: 'alex.morgan@demo.jobsmatchnow.app', title: 'Senior Product Designer', location: 'Ho Chi Minh City · Open to remote', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop', skills: ['Product strategy', 'Figma', 'Design systems', 'Research'], languages: ['English', 'Vietnamese'], experienceLevel: 'senior', completeness: 92, distanceRangeKm: 30, preferences: { desiredRoles: ['Senior Product Designer', 'Design Lead'], employmentTypes: ['Full-time'], workMode: { mode: 'hybrid', hybridDays: 2 }, salary: { min: 110000, max: 145000, currency: 'USD' }, availability: 'Now' } },
      { id: 'employer-demo', role: 'employer', demo: true, kind: 'company', name: 'Maya Chen', email: 'maya.chen@northstar.demo', title: 'Talent Partner at Northstar', company: 'Northstar', photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop', skills: ['Product strategy', 'Design systems'], languages: ['English'], experienceLevel: 'senior', completeness: 100, website: 'northstar.demo', industry: 'SaaS · Work tools', companySize: '51-200', headquarters: 'Singapore', officeLocations: ['Singapore', 'Ho Chi Minh City'], foundedYear: 2019, about: 'Northstar builds the intelligent work layer for high-growth teams across APAC. Small senior teams, high trust, and an obsession with customer craft.', benefits: ['Health insurance', 'Learning budget', 'Equity', 'Flexible hours'], techStack: ['React', 'TypeScript', 'Go', 'PostgreSQL', 'Figma'], linkedinUrl: 'linkedin.com/company/northstar-demo', contactName: 'Maya Chen', contactEmail: 'maya.chen@northstar.demo' },
      { id: 'e-2', role: 'employer', demo: true, kind: 'company', name: 'Daniel Okafor', email: 'daniel.okafor@canvaslabs.demo', title: 'Head of Talent at Canvas Labs', company: 'Canvas Labs', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop', skills: ['Leadership', 'Design systems'], languages: ['English'], experienceLevel: 'lead', completeness: 88, website: 'canvaslabs.demo', industry: 'Collaboration software', companySize: '11-50', headquarters: 'Remote · Asia', officeLocations: ['Remote', 'Ho Chi Minh City hub'], foundedYear: 2021, about: 'Canvas Labs is a remote-first maker culture building the collaboration canvas for modern creative organizations.', benefits: ['Remote budget', 'Health insurance', '13th month'], techStack: ['React', 'TypeScript', 'Node.js', 'AWS'], linkedinUrl: 'linkedin.com/company/canvas-labs-demo', contactName: 'Daniel Okafor', contactEmail: 'daniel.okafor@canvaslabs.demo' },
      { id: 'hh-1', role: 'employer', demo: true, kind: 'headhunter', name: 'Linh Pham', email: 'linh.pham@talentbridge.demo', title: 'Principal Recruiter · TalentBridge Agency', company: 'TalentBridge', photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop', skills: ['Executive search', 'Product design', 'Engineering leadership'], languages: ['English', 'Vietnamese'], experienceLevel: 'senior', completeness: 95, specializations: ['Product design', 'Engineering leadership', 'Executive search'], regions: ['Vietnam', 'APAC', 'Remote worldwide'], clients: ['Fintech scale-ups', 'Confidential consumer brands', 'Series A–C startups'], linkedinUrl: 'linkedin.com/in/linh-pham-demo', contactName: 'Linh Pham', contactEmail: 'linh.pham@talentbridge.demo' },
      { id: 'c-1', role: 'candidate', demo: true, name: 'Jordan Lee', email: 'jordan.lee@demo.jobsmatchnow.app', title: 'Staff Product Designer', location: 'Singapore', distanceKm: 5, photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop', skills: ['Design systems', 'Figma', 'Leadership', 'Research'], languages: ['English', 'Mandarin'], experienceLevel: 'lead', availability: 'Now', distanceRangeKm: 30, preferences: { desiredRoles: ['Staff Product Designer'], employmentTypes: ['Full-time'], workMode: { mode: 'hybrid', hybridDays: 3 }, salary: { min: 120000, max: 160000, currency: 'USD' }, availability: 'Now' } },
      { id: 'c-2', role: 'candidate', demo: true, name: 'Priya Raman', email: 'priya.raman@demo.jobsmatchnow.app', title: 'Senior UX Researcher', location: 'Bengaluru · Remote', distanceKm: 26, photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop', skills: ['Research', 'Product strategy', 'Analytics'], languages: ['English', 'Hindi'], experienceLevel: 'senior', availability: '2 weeks', distanceRangeKm: 50, preferences: { desiredRoles: ['Senior UX Researcher'], employmentTypes: ['Full-time', 'Contract'], workMode: { mode: 'remote' }, salary: { min: 90000, max: 120000, currency: 'USD' }, availability: '2 weeks' } },
      { id: 'c-3', role: 'candidate', demo: true, name: 'Minh Tran', email: 'minh.tran@demo.jobsmatchnow.app', title: 'Product Designer', location: 'Ho Chi Minh City', distanceKm: 12, photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop', skills: ['Figma', 'Prototyping', 'Design systems'], languages: ['English', 'Vietnamese'], experienceLevel: 'mid', availability: 'Now', distanceRangeKm: 25, preferences: { desiredRoles: ['Product Designer'], employmentTypes: ['Full-time'], workMode: { mode: 'hybrid', hybridDays: 2 }, salary: { min: 45000, max: 65000, currency: 'USD' }, availability: 'Now' } },
      { id: 'c-4', role: 'candidate', demo: true, name: 'Sofia Duarte', email: 'sofia.duarte@demo.jobsmatchnow.app', title: 'Senior Service Designer', location: 'Lisbon · Remote', distanceKm: 65, photo: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop', skills: ['Service design', 'Research', 'Facilitation'], languages: ['English', 'Portuguese'], experienceLevel: 'senior', availability: '1 month', distanceRangeKm: 40, preferences: { desiredRoles: ['Senior Service Designer'], employmentTypes: ['Full-time'], workMode: { mode: 'remote' }, salary: { min: 70000, max: 95000, currency: 'USD' }, availability: '1 month' } },
      // Pre-made accounts the mock SSO providers log into ("profile from the provider").
      { id: 'sso-linkedin-demo', role: 'candidate', demo: true, provider: 'linkedin', name: 'Taylor Nguyen', email: 'taylor.nguyen@linkedin.demo', title: 'Product Manager', location: 'Ho Chi Minh City', distanceKm: 9, photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop', skills: ['Product strategy', 'Analytics', 'Research'], languages: ['English', 'Vietnamese'], experienceLevel: 'senior', availability: 'Now', completeness: 64, distanceRangeKm: 25, preferences: { desiredRoles: ['Product Manager'], employmentTypes: ['Full-time'], workMode: { mode: 'hybrid', hybridDays: 2 }, salary: { min: 60000, max: 85000, currency: 'USD' }, availability: 'Now' } },
      { id: 'sso-google-demo', role: 'candidate', demo: true, provider: 'google', name: 'Sam Carter', email: 'sam.carter@gmail.demo', title: 'Frontend Engineer', location: 'Da Nang · Remote', distanceKm: 30, photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop', skills: ['React', 'TypeScript', 'Design systems'], languages: ['English'], experienceLevel: 'mid', availability: '2 weeks', completeness: 58, distanceRangeKm: 40, preferences: { desiredRoles: ['Frontend Engineer'], employmentTypes: ['Full-time', 'Contract'], workMode: { mode: 'remote' }, salary: { min: 55000, max: 80000, currency: 'USD' }, availability: '2 weeks' } }
    ],
    jobs: [
      { id: 'j-1', employerId: 'employer-demo', demo: true, title: 'Senior Product Designer', company: 'Northstar', logo: 'N', accent: '#3d5afe', location: 'Singapore · Hybrid', distanceKm: 7, workMode: 'Hybrid', salary: '$110k–$145k', type: 'Full-time', experienceLevel: 'senior', requiredSkills: ['Product strategy', 'Figma', 'Design systems', 'Research'], requiredLanguages: ['English'], description: 'Shape the intelligent work layer used by high-growth teams across APAC. You will own discovery through launch and raise the craft bar across our product.', mission: 'Make complex work feel beautifully simple.', culture: ['High trust', 'Customer obsessed', 'Low ego'], responseTime: '< 2 days', applicants: 84, status: 'Active', hiringRadiusKm: 40, salaryRange: { min: 110000, max: 145000, currency: 'USD' }, requiredSkillsDetail: [{ name: 'Product strategy', weight: 3 }, { name: 'Figma', weight: 3 }, { name: 'Design systems', weight: 2 }, { name: 'Research', weight: 2 }] },
      { id: 'j-2', employerId: 'e-2', demo: true, title: 'Lead Product Designer', company: 'Canvas Labs', logo: 'C', accent: '#ff5a5f', location: 'Remote · Asia', distanceKm: 18, workMode: 'Remote', remoteScope: 'worldwide', salary: '$125k–$160k', type: 'Full-time', experienceLevel: 'lead', requiredSkills: ['Figma', 'Leadership', 'Design systems'], requiredLanguages: ['English'], description: 'Lead a small, senior design team building the collaboration canvas for modern creative organizations.', mission: 'Give every team a shared space to think.', culture: ['Remote first', 'Maker culture', 'Candid'], responseTime: '3 days', applicants: 126, status: 'Active', hiringRadiusKm: 500, salaryRange: { min: 125000, max: 160000, currency: 'USD' }, requiredSkillsDetail: [{ name: 'Figma', weight: 3 }, { name: 'Leadership', weight: 3 }, { name: 'Design systems', weight: 2 }] },
      { id: 'j-3', employerId: 'e-3', demo: true, title: 'Product Design Lead, AI', company: 'Relay', logo: 'R', accent: '#00a884', location: 'London · Flexible', distanceKm: 42, workMode: 'Flexible', salary: '£95k–£125k', type: 'Full-time', experienceLevel: 'lead', requiredSkills: ['Product strategy', 'Research', 'Prototyping'], requiredLanguages: ['English'], description: 'Define human-centered AI experiences for a product helping millions navigate their working lives.', mission: 'Make opportunity visible to everyone.', culture: ['Evidence led', 'Inclusive', 'Ambitious'], responseTime: '< 1 week', applicants: 59, status: 'Active', hiringRadiusKm: 60, salaryRange: { min: 95000, max: 125000, currency: 'GBP' }, requiredSkillsDetail: [{ name: 'Product strategy', weight: 3 }, { name: 'Research', weight: 2 }, { name: 'Prototyping', weight: 2 }] },
      { id: 'j-4', employerId: 'e-4', demo: true, title: 'Senior UX Designer', company: 'Orbit Health', logo: 'O', accent: '#8b5cf6', location: 'Sydney · Hybrid', distanceKm: 75, workMode: 'Hybrid', salary: 'A$145k–A$175k', type: 'Full-time', experienceLevel: 'senior', requiredSkills: ['Research', 'Figma', 'Service design'], requiredLanguages: ['English'], description: 'Design calm, accessible patient and clinician workflows across a rapidly growing digital health platform.', mission: 'Healthcare that meets people where they are.', culture: ['Purpose driven', 'Kind', 'Rigorous'], responseTime: '4 days', applicants: 41, status: 'Active', hiringRadiusKm: 80, salaryRange: { min: 145000, max: 175000, currency: 'AUD' }, requiredSkillsDetail: [{ name: 'Research', weight: 3 }, { name: 'Figma', weight: 2 }, { name: 'Service design', weight: 2 }] },
      { id: 'j-5', employerId: 'e-2', demo: true, title: 'Senior Frontend Engineer', company: 'Canvas Labs', logo: 'C', accent: '#ff5a5f', location: 'Ho Chi Minh City · Hybrid', distanceKm: 11, workMode: 'Hybrid', salary: '$85k–$115k', type: 'Full-time', experienceLevel: 'senior', requiredSkills: ['React', 'TypeScript', 'Design systems'], requiredLanguages: ['English'], description: 'Build the real-time collaboration surface of the canvas with a design-obsessed product team.', mission: 'Give every team a shared space to think.', culture: ['Remote first', 'Maker culture', 'Candid'], responseTime: '2 days', applicants: 63, status: 'Active', hiringRadiusKm: 40, salaryRange: { min: 85000, max: 115000, currency: 'USD' }, requiredSkillsDetail: [{ name: 'React', weight: 3 }, { name: 'TypeScript', weight: 3 }, { name: 'Design systems', weight: 1 }] },
      { id: 'j-6', employerId: 'hh-1', demo: true, title: 'Head of Product Design (confidential client)', company: 'TalentBridge · client brief', logo: 'T', accent: '#f59e0b', location: 'Ho Chi Minh City · On-site', distanceKm: 6, workMode: 'On-site', salary: '$130k–$170k', type: 'Full-time', experienceLevel: 'lead', requiredSkills: ['Leadership', 'Product strategy', 'Design systems'], requiredLanguages: ['English', 'Vietnamese'], description: 'Our client, a fast-scaling fintech, is hiring its first Head of Product Design to build a 10-person team across two hubs.', mission: 'Placed by TalentBridge on behalf of a confidential client.', culture: ['Ambitious', 'Ownership', 'Bilingual team'], responseTime: '< 3 days', applicants: 22, status: 'Active', hiringRadiusKm: 25, salaryRange: { min: 130000, max: 170000, currency: 'USD' }, requiredSkillsDetail: [{ name: 'Leadership', weight: 3 }, { name: 'Product strategy', weight: 2 }, { name: 'Design systems', weight: 2 }] }
    ],
    swipes: [
      { id: 's-seed-1', actorId: 'employer-demo', targetType: 'candidate', targetId: 'candidate-demo', direction: 'like', superLike: true, createdAt: now - 3600000 }
    ],
    matches: [
      { id: 'm-candidate', candidateId: 'candidate-demo', employerId: 'e-3', jobId: 'j-3', stage: 'Matched', createdAt: now - 86400000 * 3 },
      { id: 'm-existing', candidateId: 'c-1', employerId: 'employer-demo', jobId: 'j-1', stage: 'Interview', createdAt: now - 86400000 * 2 },
      { id: 'm-priya', candidateId: 'c-2', employerId: 'employer-demo', jobId: 'j-1', stage: 'Matched', createdAt: now - 86400000 * 6 }
    ],
    messages: [
      { id: 'msg-candidate-1', matchId: 'm-candidate', senderId: 'e-3', text: 'Hi Alex — your product strategy work looks highly relevant to what we’re building at Relay.', createdAt: now - 10800000 },
      { id: 'msg-1', matchId: 'm-existing', senderId: 'employer-demo', text: 'Hi Jordan — your systems work really stood out. Would you be open to a 25-minute intro this week?', createdAt: now - 7200000 },
      { id: 'msg-2', matchId: 'm-existing', senderId: 'c-1', text: 'Absolutely. Thursday afternoon works well for me.', createdAt: now - 5400000 }
    ],
    calls: [
      { id: 'call-existing', matchId: 'm-existing', createdBy: 'employer-demo', title: 'Intro call — Senior Product Designer', startAt: now + 86400000 * 2, durationMinutes: 25, notes: 'Quick intro, no need to prepare anything.', createdAt: now - 5000000 }
    ],
    feedback: [
      { id: 'fb-1', type: 'review', approved: true, name: 'Mai N.', role: 'Product Designer', rating: 5, message: 'Matched with two companies in my city in a week. The salary-up-front part is a game changer — no more guessing.', createdAt: now - 86400000 * 2 },
      { id: 'fb-2', type: 'review', approved: true, name: 'David O.', role: 'Head of Talent', rating: 5, message: 'We stopped drowning in unqualified applications. Mutual intent means every conversation is worth having.', createdAt: now - 86400000 * 4 },
      { id: 'fb-3', type: 'review', approved: true, name: 'Priya R.', role: 'UX Researcher', rating: 4, message: 'Love the explainable fit score — I finally understand why a role is a good match before I even swipe.', createdAt: now - 86400000 * 6 },
      { id: 'fb-4', type: 'review', approved: true, name: 'Tuan L.', role: 'Frontend Engineer', rating: 5, message: 'Met a recruiter for coffee 2 km from my apartment. Feels human, not like a job board.', createdAt: now - 86400000 * 9 }
    ]
  };
}
