export function createSeed() {
  const now = Date.now();
  const fullTimeHybrid = {
    employmentTypes: ['Full-time'],
    workMode: { mode: 'hybrid', hybridDays: 2 },
  };

  /* Sarah's roles each carry the same 5-candidate mutual-match pool (j-1's
     match set already exists below) so every one of her 10 job offers shows
     5 mutual matches without inventing a new cast per role. */
  const sarahCandidatePool = [
    { id: 'candidate-demo', name: 'sofia', stage: 'Matched' },
    { id: 'c-1', name: 'david', stage: 'Interview' },
    { id: 'c-2', name: 'maria', stage: 'Matched' },
    { id: 'c-3', name: 'john', stage: 'Matched' },
    { id: 'c-4', name: 'linh', stage: 'Matched' },
  ];
  const sarahExtraJobIds = ['j-sarah-cloud', 'j-sarah-devops', 'j-sarah-data', 'j-sarah-frontend', 'j-sarah-backend', 'j-sarah-security', 'j-sarah-mobile', 'j-sarah-product', 'j-sarah-qa'];
  const sarahExtraMatches = sarahExtraJobIds.flatMap((jobId, jobIndex) => sarahCandidatePool.map((cand, i) => ({
    id: `m-${cand.name}-${jobId}`,
    demoTemplate: true,
    candidateId: cand.id,
    employerId: 'employer-demo',
    jobId,
    stage: cand.stage,
    createdAt: now - (jobIndex * 6 + i + 1) * 3600000,
  })));

  return {
    users: [
      {
        id: 'candidate-demo',
        demoTemplate: true,
        role: 'candidate',
        demo: true,
        name: 'Sofia Okafor',
        email: 'sofia.okafor@demo.jobsmatchnow.app',
        title: 'Senior AI Product Manager',
        location: 'Ho Chi Minh City',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        distanceKm: 7,
        photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
        skills: ['AWS', 'Azure', 'Python', 'Machine learning', 'TensorFlow', 'MLOps', 'Kubernetes', 'Terraform', 'Cloud architecture', 'Product strategy', 'Leadership'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        completeness: 73,
        availability: '2 weeks',
        distanceRangeKm: 40,
        preferences: {
          ...fullTimeHybrid,
          desiredRoles: ['Lead AI Engineer', 'Senior AI Platform Engineer', 'Cloud Solutions Architect'],
          salary: { min: 84000, max: 145000, currency: 'USD' },
          availability: '2 weeks',
        },
      },
      {
        id: 'employer-demo',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'Sarah Thompson',
        email: 'sarah.thompson@aws.demo',
        title: 'HR Talent Partner',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
        skills: ['AI recruiting', 'Cloud engineering', 'Talent strategy'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'aws.amazon.com',
        industry: 'Cloud computing',
        companySize: '10,000+',
        headquarters: 'Seattle',
        officeLocations: ['Ho Chi Minh City', 'Singapore', 'Remote'],
        about: 'AWS helps organizations build, deploy, and scale securely in the cloud.',
        benefits: ['Health insurance', 'Learning budget', 'Equity', 'Flexible hours'],
        techStack: ['AWS', 'Python', 'TensorFlow', 'Kubernetes', 'MLOps'],
        linkedinUrl: 'linkedin.com/company/amazon-web-services',
        contactName: 'Sarah Thompson',
        contactEmail: 'sarah.thompson@aws.demo',
      },
      {
        id: 'employer-demo-2',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'Marcus Chen',
        email: 'marcus.chen@google.demo',
        title: 'Technical Recruiter',
        company: 'Google',
        companyLogo: 'https://logo.clearbit.com/google.com',
        photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop',
        skills: ['Technical recruiting', 'Engineering leadership'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'google.com',
        industry: 'Software',
        companySize: '10,000+',
        headquarters: 'Mountain View',
        officeLocations: ['Singapore', 'Remote'],
        about: 'Google builds products that help billions of people every day.',
        benefits: ['Health insurance', 'Learning budget', 'Equity', 'Free meals'],
        techStack: ['Go', 'Python', 'Kubernetes', 'TensorFlow'],
        contactName: 'Marcus Chen',
        contactEmail: 'marcus.chen@google.demo',
      },
      {
        id: 'employer-demo-3',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'Priya Nair',
        email: 'priya.nair@stripe.demo',
        title: 'Talent Partner',
        company: 'Stripe',
        companyLogo: 'https://logo.clearbit.com/stripe.com',
        photo: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop',
        skills: ['Fintech recruiting', 'Payments engineering'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'stripe.com',
        industry: 'Financial infrastructure',
        companySize: '5,000+',
        headquarters: 'San Francisco',
        officeLocations: ['Singapore', 'Remote'],
        about: 'Stripe builds economic infrastructure for the internet.',
        benefits: ['Health insurance', 'Equity', 'Remote stipend'],
        techStack: ['Ruby', 'Go', 'AWS', 'PostgreSQL'],
        contactName: 'Priya Nair',
        contactEmail: 'priya.nair@stripe.demo',
      },
      {
        id: 'employer-demo-4',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'David Kim',
        email: 'david.kim@netflix.demo',
        title: 'Head of Talent',
        company: 'Netflix',
        companyLogo: 'https://logo.clearbit.com/netflix.com',
        photo: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400&h=400&fit=crop',
        skills: ['Media tech recruiting', 'Streaming platforms'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'netflix.com',
        industry: 'Entertainment technology',
        companySize: '10,000+',
        headquarters: 'Los Gatos',
        officeLocations: ['Singapore', 'Remote'],
        about: 'Netflix entertains the world with data-driven streaming technology.',
        benefits: ['Health insurance', 'Unlimited PTO', 'Equity'],
        techStack: ['Java', 'Python', 'AWS', 'Kafka'],
        contactName: 'David Kim',
        contactEmail: 'david.kim@netflix.demo',
      },
      {
        id: 'employer-demo-5',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'Elena Rossi',
        email: 'elena.rossi@spotify.demo',
        title: 'People Partner',
        company: 'Spotify',
        companyLogo: 'https://logo.clearbit.com/spotify.com',
        photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
        skills: ['Product recruiting', 'Music tech'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'spotify.com',
        industry: 'Audio streaming',
        companySize: '5,000+',
        headquarters: 'Stockholm',
        officeLocations: ['Singapore', 'Remote'],
        about: 'Spotify unlocks the potential of human creativity through audio.',
        benefits: ['Health insurance', 'Learning budget', 'Flexible hours'],
        techStack: ['Python', 'Java', 'GCP', 'Kubernetes'],
        contactName: 'Elena Rossi',
        contactEmail: 'elena.rossi@spotify.demo',
      },
      {
        id: 'employer-demo-6',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'James Okoro',
        email: 'james.okoro@shopify.demo',
        title: 'Talent Acquisition Lead',
        company: 'Shopify',
        companyLogo: 'https://logo.clearbit.com/shopify.com',
        photo: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
        skills: ['E-commerce recruiting', 'Platform engineering'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 100,
        website: 'shopify.com',
        industry: 'E-commerce',
        companySize: '10,000+',
        headquarters: 'Ottawa',
        officeLocations: ['Remote'],
        about: 'Shopify makes commerce better for everyone.',
        benefits: ['Health insurance', 'Equity', 'Remote first'],
        techStack: ['Ruby', 'React', 'GraphQL', 'MySQL'],
        contactName: 'James Okoro',
        contactEmail: 'james.okoro@shopify.demo',
      },
      {
        id: 'candidate-demo-2',
        demoTemplate: true,
        demoOrder: 5,
        role: 'candidate',
        demo: true,
        name: 'Daniel Osei',
        email: 'daniel.osei@demo.jobsmatchnow.app',
        title: 'Senior Product Designer',
        company: 'Canva',
        location: 'Ho Chi Minh City',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        distanceKm: 6,
        photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
        skills: ['Figma', 'Design systems', 'Prototyping', 'User research'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: 'Now',
        distanceRangeKm: 30,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Senior Product Designer'], salary: { min: 70000, max: 100000, currency: 'USD' }, availability: 'Now' },
      },
      {
        id: 'candidate-demo-3',
        demoTemplate: true,
        demoOrder: 6,
        role: 'candidate',
        demo: true,
        name: 'Grace Kim',
        email: 'grace.kim@demo.jobsmatchnow.app',
        title: 'Data Engineer',
        company: 'Grab',
        location: 'Singapore',
        city: 'Singapore',
        country: 'Singapore',
        distanceKm: 10,
        photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
        skills: ['Python', 'SQL', 'Spark', 'Airflow', 'AWS'],
        languages: ['English', 'Korean'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: '2 weeks',
        distanceRangeKm: 25,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Data Engineer'], salary: { min: 85000, max: 120000, currency: 'USD' }, availability: '2 weeks' },
      },
      {
        id: 'candidate-demo-4',
        demoTemplate: true,
        demoOrder: 7,
        role: 'candidate',
        demo: true,
        name: "Liam O'Connor",
        email: 'liam.oconnor@demo.jobsmatchnow.app',
        title: 'Backend Engineer',
        company: 'Atlassian',
        location: 'Da Nang, Vietnam',
        city: 'Da Nang',
        country: 'Vietnam',
        distanceKm: 14,
        photo: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400&h=400&fit=crop',
        skills: ['Node.js', 'PostgreSQL', 'AWS', 'Kubernetes', 'Go'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: '1 month',
        distanceRangeKm: 40,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Backend Engineer'], salary: { min: 90000, max: 125000, currency: 'USD' }, availability: '1 month' },
      },
      {
        id: 'e-2',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'David Chen',
        email: 'david.chen@microsoft.demo',
        title: 'Engineering Recruiter',
        company: 'Microsoft',
        companyLogo: 'https://logo.clearbit.com/microsoft.com',
        photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
        skills: ['AI recruiting', 'Platform engineering'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 96,
        website: 'microsoft.com',
        industry: 'Software',
        companySize: '10,000+',
        headquarters: 'Redmond',
        officeLocations: ['Ho Chi Minh City', 'Remote'],
        about: 'Microsoft builds platforms and AI products used around the world.',
        benefits: ['Health insurance', 'Learning budget', 'Stock'],
        techStack: ['Azure', 'Python', 'MLOps', 'Kubernetes'],
        contactName: 'David Chen',
        contactEmail: 'david.chen@microsoft.demo',
      },
      {
        id: 'hh-1',
        demoTemplate: true,
        role: 'employer',
        demo: true,
        kind: 'company',
        name: 'Maria Lopez',
        email: 'maria.lopez@rackspace.demo',
        title: 'Talent Acquisition',
        company: 'Rackspace Technology',
        companyLogo: 'https://logo.clearbit.com/rackspace.com',
        photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
        skills: ['Cloud recruiting', 'Engineering leadership'],
        languages: ['English'],
        experienceLevel: 'senior',
        completeness: 95,
        website: 'rackspace.com',
        industry: 'Cloud services',
        companySize: '5,000+',
        headquarters: 'San Antonio',
        officeLocations: ['Remote', 'Singapore'],
        about: 'Rackspace Technology designs, builds, and operates multicloud solutions.',
        benefits: ['Remote work', 'Health insurance', 'Learning budget'],
        techStack: ['AWS', 'Azure', 'Kubernetes', 'Terraform'],
        contactName: 'Maria Lopez',
        contactEmail: 'maria.lopez@rackspace.demo',
      },
      {
        id: 'c-1',
        demoTemplate: true,
        demoOrder: 1,
        role: 'candidate',
        demo: true,
        name: 'David Nguyen',
        email: 'david.nguyen@demo.jobsmatchnow.app',
        title: 'Senior AI Engineer',
        company: 'Google',
        location: 'Ho Chi Minh City',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        distanceKm: 5,
        photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
        skills: ['Python', 'TensorFlow', 'AWS', 'MLOps'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: '2 weeks',
        distanceRangeKm: 30,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Lead AI Engineer'], salary: { min: 85000, max: 120000, currency: 'USD' }, availability: '2 weeks' },
      },
      {
        id: 'c-2',
        demoTemplate: true,
        demoOrder: 2,
        role: 'candidate',
        demo: true,
        name: 'Maria Garcia',
        email: 'maria.garcia@demo.jobsmatchnow.app',
        title: 'Machine Learning Engineer',
        company: 'Microsoft',
        location: 'Ho Chi Minh City',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        distanceKm: 8,
        photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
        skills: ['Python', 'TensorFlow', 'AWS', 'MLOps', 'PyTorch'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: 'Now',
        distanceRangeKm: 35,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Lead AI Engineer'], salary: { min: 80000, max: 115000, currency: 'USD' }, availability: 'Now' },
      },
      {
        id: 'c-3',
        demoTemplate: true,
        demoOrder: 3,
        role: 'candidate',
        demo: true,
        name: 'John Smith',
        email: 'john.smith@demo.jobsmatchnow.app',
        title: 'AI Solutions Architect',
        company: 'AWS',
        location: 'Da Nang, Vietnam',
        city: 'Da Nang',
        country: 'Vietnam',
        distanceKm: 12,
        photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        skills: ['Python', 'TensorFlow', 'AWS', 'MLOps', 'SageMaker', 'Docker'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: '1 month',
        distanceRangeKm: 40,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Lead AI Engineer'], salary: { min: 90000, max: 120000, currency: 'USD' }, availability: '1 month' },
      },
      {
        id: 'c-4',
        demoTemplate: true,
        demoOrder: 4,
        role: 'candidate',
        demo: true,
        name: 'Linh Tran',
        email: 'linh.tran@demo.jobsmatchnow.app',
        title: 'Data Scientist',
        company: 'VinAI',
        location: 'Ho Chi Minh City',
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        distanceKm: 9,
        photo: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        skills: ['Python', 'TensorFlow', 'AWS', 'MLOps', 'SQL'],
        languages: ['English'],
        experienceLevel: 'senior',
        seniority: 'senior',
        availability: 'Now',
        distanceRangeKm: 30,
        preferences: { ...fullTimeHybrid, desiredRoles: ['Lead AI Engineer'], salary: { min: 78000, max: 108000, currency: 'USD' }, availability: 'Now' },
      },
    ],
    jobs: [
      {
        id: 'j-1',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Lead AI Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Ho Chi Minh City',
        distanceKm: 7,
        workMode: 'Hybrid',
        hybridDays: 2,
        salary: '$6,000-$9,000 / month',
        salaryRange: { min: 72000, max: 108000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        seniority: 'senior',
        requiredSkills: ['Python', 'TensorFlow', 'AWS', 'MLOps'],
        requiredSkillsDetail: [{ name: 'Python', weight: 3 }, { name: 'TensorFlow', weight: 3 }, { name: 'AWS', weight: 3 }, { name: 'MLOps', weight: 2 }],
        requiredLanguages: ['English'],
        description: 'Lead the design and delivery of production AI services on AWS.',
        mission: 'Make enterprise AI reliable, secure, and useful.',
        culture: ['Customer obsessed', 'Ownership', 'Invent and simplify'],
        responseTime: '< 2 days',
        applicants: 127,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-2',
        demoTemplate: true,
        employerId: 'e-2',
        demo: true,
        title: 'Senior AI Platform Engineer',
        company: 'Microsoft',
        companyLogo: 'https://logo.clearbit.com/microsoft.com',
        logo: 'M',
        accent: '#00a4ef',
        location: 'Ho Chi Minh City',
        distanceKm: 9,
        workMode: 'Hybrid',
        hybridDays: 2,
        salary: '$5,000-$7,500 / month',
        salaryRange: { min: 60000, max: 90000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        seniority: 'senior',
        requiredSkills: ['Python', 'Azure', 'MLOps', 'Kubernetes'],
        requiredSkillsDetail: [{ name: 'Python', weight: 3 }, { name: 'Azure', weight: 3 }, { name: 'MLOps', weight: 2 }, { name: 'Kubernetes', weight: 2 }],
        requiredLanguages: ['English'],
        description: 'Build the platform that powers secure AI workloads across Microsoft products.',
        mission: 'Empower every person and organization to achieve more with AI.',
        culture: ['Growth mindset', 'Inclusive', 'Customer focused'],
        responseTime: '2 days',
        applicants: 96,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-6',
        demoTemplate: true,
        employerId: 'hh-1',
        demo: true,
        title: 'Cloud Solutions Architect',
        company: 'Rackspace Technology',
        companyLogo: 'https://logo.clearbit.com/rackspace.com',
        logo: 'R',
        accent: '#e31b23',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'worldwide',
        salary: '$4,500-$7,000 / month',
        salaryRange: { min: 54000, max: 84000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        seniority: 'senior',
        requiredSkills: ['AWS', 'Terraform', 'Kubernetes', 'Cloud architecture'],
        requiredSkillsDetail: [{ name: 'AWS', weight: 3 }, { name: 'Terraform', weight: 3 }, { name: 'Kubernetes', weight: 2 }, { name: 'Cloud architecture', weight: 2 }],
        requiredLanguages: ['English'],
        description: 'Design resilient multicloud platforms for global customers.',
        mission: 'Be the best partner for multicloud transformation.',
        culture: ['Remote first', 'Customer committed', 'Collaborative'],
        responseTime: '< 3 days',
        applicants: 72,
        status: 'Active',
        hiringRadiusKm: 500,
      },
      {
        id: 'j-sarah-cloud',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Cloud Architect',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Singapore',
        distanceKm: 12,
        workMode: 'Hybrid',
        salary: '$7,000-$10,000 / month',
        salaryRange: { min: 84000, max: 120000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['AWS', 'Terraform', 'Kubernetes', 'Cloud architecture'],
        requiredLanguages: ['English'],
        description: 'Design secure cloud architectures for enterprise customers.',
        mission: 'Help customers build well-architected cloud systems.',
        culture: ['Ownership', 'Customer obsessed'],
        responseTime: '2 days',
        applicants: 88,
        status: 'Active',
        hiringRadiusKm: 50,
      },
      {
        id: 'j-sarah-devops',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'DevOps Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'worldwide',
        salary: '$5,500-$8,000 / month',
        salaryRange: { min: 66000, max: 96000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
        requiredLanguages: ['English'],
        description: 'Automate reliable delivery across cloud services.',
        mission: 'Make deployment safe and fast.',
        culture: ['Ownership', 'Automation first'],
        responseTime: '2 days',
        applicants: 64,
        status: 'Active',
        hiringRadiusKm: 500,
      },
      {
        id: 'j-sarah-data',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Data Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Ho Chi Minh City',
        distanceKm: 8,
        workMode: 'Hybrid',
        salary: '$5,000-$7,500 / month',
        salaryRange: { min: 60000, max: 90000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Python', 'SQL', 'AWS', 'Data pipelines'],
        requiredLanguages: ['English'],
        description: 'Build scalable data foundations for AI products.',
        mission: 'Make trusted data available to every team.',
        culture: ['Ownership', 'Data driven'],
        responseTime: '2 days',
        applicants: 51,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-sarah-frontend',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Frontend Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Ho Chi Minh City',
        distanceKm: 6,
        workMode: 'Hybrid',
        salary: '$4,500-$7,000 / month',
        salaryRange: { min: 54000, max: 84000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['TypeScript', 'React', 'AWS', 'GraphQL'],
        requiredLanguages: ['English'],
        description: 'Build fast, accessible interfaces for millions of AWS console users.',
        mission: 'Make the cloud console a delight to use.',
        culture: ['Customer obsessed', 'Craftsmanship'],
        responseTime: '2 days',
        applicants: 58,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-sarah-backend',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Backend Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Singapore',
        distanceKm: 11,
        workMode: 'Hybrid',
        salary: '$6,500-$9,500 / month',
        salaryRange: { min: 78000, max: 114000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Java', 'AWS', 'Distributed systems', 'DynamoDB'],
        requiredLanguages: ['English'],
        description: 'Design and scale the services behind core AWS APIs.',
        mission: 'Keep the cloud fast, available, and secure.',
        culture: ['Ownership', 'Operational excellence'],
        responseTime: '< 2 days',
        applicants: 83,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-sarah-security',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Security Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'worldwide',
        salary: '$6,000-$9,000 / month',
        salaryRange: { min: 72000, max: 108000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['AWS', 'Security', 'IAM', 'Threat modeling'],
        requiredLanguages: ['English'],
        description: 'Protect customer workloads at planet scale.',
        mission: 'Security is job zero.',
        culture: ['Ownership', 'High trust'],
        responseTime: '2 days',
        applicants: 47,
        status: 'Active',
        hiringRadiusKm: 500,
      },
      {
        id: 'j-sarah-mobile',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Mobile Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Ho Chi Minh City',
        distanceKm: 7,
        workMode: 'Hybrid',
        salary: '$5,000-$7,500 / month',
        salaryRange: { min: 60000, max: 90000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'mid',
        requiredSkills: ['Kotlin', 'Swift', 'AWS', 'Mobile architecture'],
        requiredLanguages: ['English'],
        description: 'Build the mobile console experience for AWS customers on the go.',
        mission: 'Make cloud management possible from anywhere.',
        culture: ['Craftsmanship', 'Customer obsessed'],
        responseTime: '3 days',
        applicants: 39,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-sarah-product',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'Technical Product Manager',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Singapore',
        distanceKm: 13,
        workMode: 'Hybrid',
        salary: '$7,500-$11,000 / month',
        salaryRange: { min: 90000, max: 132000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Product strategy', 'AWS', 'Roadmaps', 'Stakeholder management'],
        requiredLanguages: ['English'],
        description: 'Own the roadmap for a core AWS AI service.',
        mission: 'Turn customer problems into products people love.',
        culture: ['Customer obsessed', 'Invent and simplify'],
        responseTime: '2 days',
        applicants: 61,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-sarah-qa',
        demoTemplate: true,
        employerId: 'employer-demo',
        demo: true,
        title: 'QA / SDET Engineer',
        company: 'AWS',
        companyLogo: 'https://logo.clearbit.com/aws.amazon.com',
        logo: 'aws',
        accent: '#ff9900',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'country',
        country: 'Vietnam',
        salary: '$4,000-$6,000 / month',
        salaryRange: { min: 48000, max: 72000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'mid',
        requiredSkills: ['Test automation', 'AWS', 'CI/CD', 'Python'],
        requiredLanguages: ['English'],
        description: 'Build automated test systems that keep releases safe.',
        mission: 'Ship fast without breaking trust.',
        culture: ['Ownership', 'Automation first'],
        responseTime: '3 days',
        applicants: 34,
        status: 'Active',
        hiringRadiusKm: 500,
      },
      {
        id: 'j-google-frontend',
        demoTemplate: true,
        employerId: 'employer-demo-2',
        demo: true,
        title: 'Senior Frontend Engineer',
        company: 'Google',
        companyLogo: 'https://logo.clearbit.com/google.com',
        logo: 'G',
        accent: '#4285f4',
        location: 'Singapore',
        distanceKm: 10,
        workMode: 'Hybrid',
        salary: '$7,000-$10,500 / month',
        salaryRange: { min: 84000, max: 126000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['TypeScript', 'React', 'GraphQL', 'Testing'],
        requiredLanguages: ['English'],
        description: 'Build delightful, high-performance web experiences at scale.',
        mission: 'Organize the world’s information and make it universally accessible.',
        culture: ['Innovative', 'Data driven', 'Collaborative'],
        responseTime: '3 days',
        applicants: 142,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-stripe-backend',
        demoTemplate: true,
        employerId: 'employer-demo-3',
        demo: true,
        title: 'Backend Engineer, Payments',
        company: 'Stripe',
        companyLogo: 'https://logo.clearbit.com/stripe.com',
        logo: 'S',
        accent: '#635bff',
        location: 'Singapore',
        distanceKm: 9,
        workMode: 'Hybrid',
        salary: '$7,500-$11,000 / month',
        salaryRange: { min: 90000, max: 132000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Ruby', 'Go', 'AWS', 'Distributed systems'],
        requiredLanguages: ['English'],
        description: 'Build the infrastructure that moves money for millions of businesses.',
        mission: 'Increase the GDP of the internet.',
        culture: ['Rigorous', 'Users first', 'Move with urgency'],
        responseTime: '2 days',
        applicants: 97,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-netflix-data',
        demoTemplate: true,
        employerId: 'employer-demo-4',
        demo: true,
        title: 'Senior Data Engineer',
        company: 'Netflix',
        companyLogo: 'https://logo.clearbit.com/netflix.com',
        logo: 'N',
        accent: '#e50914',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'worldwide',
        salary: '$8,000-$12,000 / month',
        salaryRange: { min: 96000, max: 144000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Python', 'Spark', 'AWS', 'Data pipelines'],
        requiredLanguages: ['English'],
        description: 'Build the data platform behind personalized streaming for 250M+ members.',
        mission: 'Entertain the world.',
        culture: ['Freedom and responsibility', 'High performance'],
        responseTime: '3 days',
        applicants: 118,
        status: 'Active',
        hiringRadiusKm: 500,
      },
      {
        id: 'j-spotify-design',
        demoTemplate: true,
        employerId: 'employer-demo-5',
        demo: true,
        title: 'Senior Product Designer',
        company: 'Spotify',
        companyLogo: 'https://logo.clearbit.com/spotify.com',
        logo: 'Sp',
        accent: '#1db954',
        location: 'Singapore',
        distanceKm: 12,
        workMode: 'Hybrid',
        salary: '$6,500-$9,500 / month',
        salaryRange: { min: 78000, max: 114000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'senior',
        requiredSkills: ['Figma', 'Design systems', 'Prototyping', 'User research'],
        requiredLanguages: ['English'],
        description: 'Shape the listening experience for hundreds of millions of users.',
        mission: 'Unlock the potential of human creativity.',
        culture: ['Innovative', 'Collaborative', 'Playful'],
        responseTime: '2 days',
        applicants: 76,
        status: 'Active',
        hiringRadiusKm: 40,
      },
      {
        id: 'j-shopify-eng-manager',
        demoTemplate: true,
        employerId: 'employer-demo-6',
        demo: true,
        title: 'Engineering Manager',
        company: 'Shopify',
        companyLogo: 'https://logo.clearbit.com/shopify.com',
        logo: 'Sh',
        accent: '#95bf47',
        location: 'Remote',
        distanceKm: 0,
        workMode: 'Remote',
        remoteScope: 'worldwide',
        salary: '$9,000-$13,000 / month',
        salaryRange: { min: 108000, max: 156000, currency: 'USD' },
        type: 'Full-time',
        experienceLevel: 'lead',
        requiredSkills: ['Ruby', 'Engineering leadership', 'React', 'GraphQL'],
        requiredLanguages: ['English'],
        description: 'Lead a team building commerce tools for a million+ merchants.',
        mission: 'Make commerce better for everyone.',
        culture: ['Remote first', 'Trust', 'Craftsmanship'],
        responseTime: '3 days',
        applicants: 64,
        status: 'Active',
        hiringRadiusKm: 500,
      },
    ],
    swipes: [
      { id: 's-sarah-sofia', demoTemplate: true, actorId: 'employer-demo', targetType: 'candidate', targetId: 'candidate-demo', jobId: 'j-1', direction: 'like', superLike: true, createdAt: now - 3600000 },
      { id: 's-microsoft-sofia', demoTemplate: true, actorId: 'e-2', targetType: 'candidate', targetId: 'candidate-demo', jobId: 'j-2', direction: 'like', createdAt: now - 5400000 },
      { id: 's-rackspace-sofia', demoTemplate: true, actorId: 'hh-1', targetType: 'candidate', targetId: 'candidate-demo', jobId: 'j-6', direction: 'like', createdAt: now - 7200000 },
      { id: 's-sofia-aws', demoTemplate: true, actorId: 'candidate-demo', targetType: 'job', targetId: 'j-1', direction: 'like', createdAt: now - 3000000 },
      { id: 's-sofia-microsoft', demoTemplate: true, actorId: 'candidate-demo', targetType: 'job', targetId: 'j-2', direction: 'like', createdAt: now - 4800000 },
      { id: 's-sofia-rackspace', demoTemplate: true, actorId: 'candidate-demo', targetType: 'job', targetId: 'j-6', direction: 'like', createdAt: now - 6600000 },
      { id: 's-david-aws', demoTemplate: true, actorId: 'c-1', targetType: 'job', targetId: 'j-1', direction: 'like', createdAt: now - 1800000 },
      { id: 's-maria-aws', demoTemplate: true, actorId: 'c-2', targetType: 'job', targetId: 'j-1', direction: 'like', createdAt: now - 2400000 },
      { id: 's-john-aws', demoTemplate: true, actorId: 'c-3', targetType: 'job', targetId: 'j-1', direction: 'like', createdAt: now - 3000000 },
      { id: 's-linh-aws', demoTemplate: true, actorId: 'c-4', targetType: 'job', targetId: 'j-1', direction: 'like', createdAt: now - 3600000 },
      { id: 's-sarah-david', demoTemplate: true, actorId: 'employer-demo', targetType: 'candidate', targetId: 'c-1', jobId: 'j-1', direction: 'like', createdAt: now - 1200000 },
      { id: 's-sarah-maria', demoTemplate: true, actorId: 'employer-demo', targetType: 'candidate', targetId: 'c-2', jobId: 'j-1', direction: 'like', createdAt: now - 1500000 },
      { id: 's-sarah-john', demoTemplate: true, actorId: 'employer-demo', targetType: 'candidate', targetId: 'c-3', jobId: 'j-1', direction: 'like', createdAt: now - 1900000 },
      { id: 's-sarah-linh', demoTemplate: true, actorId: 'employer-demo', targetType: 'candidate', targetId: 'c-4', jobId: 'j-1', direction: 'like', createdAt: now - 2100000 },
    ],
    matches: [
      { id: 'm-sofia-aws', demoTemplate: true, candidateId: 'candidate-demo', employerId: 'employer-demo', jobId: 'j-1', stage: 'Matched', createdAt: now - 86400000 },
      { id: 'm-sofia-microsoft', demoTemplate: true, candidateId: 'candidate-demo', employerId: 'e-2', jobId: 'j-2', stage: 'Matched', createdAt: now - 86400000 * 2 },
      { id: 'm-sofia-rackspace', demoTemplate: true, candidateId: 'candidate-demo', employerId: 'hh-1', jobId: 'j-6', stage: 'Matched', createdAt: now - 86400000 * 3 },
      { id: 'm-david-aws', demoTemplate: true, candidateId: 'c-1', employerId: 'employer-demo', jobId: 'j-1', stage: 'Interview', createdAt: now - 86400000 * 2 },
      { id: 'm-maria-aws', demoTemplate: true, candidateId: 'c-2', employerId: 'employer-demo', jobId: 'j-1', stage: 'Matched', createdAt: now - 86400000 * 3 },
      { id: 'm-john-aws', demoTemplate: true, candidateId: 'c-3', employerId: 'employer-demo', jobId: 'j-1', stage: 'Matched', createdAt: now - 86400000 * 4 },
      { id: 'm-linh-aws', demoTemplate: true, candidateId: 'c-4', employerId: 'employer-demo', jobId: 'j-1', stage: 'Matched', createdAt: now - 86400000 * 5 },
      ...sarahExtraMatches,
    ],
    messages: [
      { id: 'msg-sofia-aws', demoTemplate: true, matchId: 'm-sofia-aws', senderId: 'employer-demo', text: 'Your AI and cloud background looks ideal for our Lead AI Engineer role.', createdAt: now - 7200000 },
      { id: 'msg-sofia-microsoft', demoTemplate: true, matchId: 'm-sofia-microsoft', senderId: 'e-2', text: 'Would you be available for a coffee chat about our AI platform team?', createdAt: now - 10800000 },
      { id: 'msg-sofia-rackspace', demoTemplate: true, matchId: 'm-sofia-rackspace', senderId: 'hh-1', text: 'Your cloud architecture experience stood out to us.', createdAt: now - 14400000 },
      { id: 'msg-david-aws', demoTemplate: true, matchId: 'm-david-aws', senderId: 'c-1', text: 'Thursday afternoon works well for me.', createdAt: now - 5400000 },
      { id: 'msg-maria-aws', demoTemplate: true, matchId: 'm-maria-aws', senderId: 'c-2', text: 'I would love to learn more about the role.', createdAt: now - 6200000 },
      { id: 'msg-john-aws', demoTemplate: true, matchId: 'm-john-aws', senderId: 'c-3', text: 'The AWS AI mission is a strong fit for me.', createdAt: now - 6800000 },
    ],
    calls: [
      { id: 'call-david-aws', demoTemplate: true, matchId: 'm-david-aws', createdBy: 'employer-demo', title: 'Coffee chat - David Nguyen', startAt: now + 86400000, durationMinutes: 25, notes: 'Introductory conversation.', createdAt: now - 3600000 },
      { id: 'call-maria-aws', demoTemplate: true, matchId: 'm-maria-aws', createdBy: 'employer-demo', title: 'Coffee chat - Maria Garcia', startAt: now + 86400000 * 2, durationMinutes: 25, notes: 'AI platform conversation.', createdAt: now - 4200000 },
    ],
    bookmarks: [],
    feedback: [
      { id: 'fb-1', type: 'review', approved: true, name: 'Mai N.', role: 'Product Designer', rating: 5, message: 'Matched with two companies in my city in a week. The salary-up-front part is a game changer.', createdAt: now - 86400000 * 2 },
      { id: 'fb-2', type: 'review', approved: true, name: 'David O.', role: 'Head of Talent', rating: 5, message: 'Mutual intent means every conversation is worth having.', createdAt: now - 86400000 * 4 },
    ],
  };
}
